# Generated by Django 4.2.29 on 2026-04-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_slug_post_slug_alter_post_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='category',
            name='color_hex',
            field=models.CharField(default='#FFC107', max_length=7),
        ),
    ]
